### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jthurston** [Benj4865/Skadis-Pegboard_SVG_Generator#1]
Hey thanks for making this. Ran it on my MAC just with a python command and it worked okay.

**Comment by Benj4865** [comment]
Hey Jeff

I would love to, but I cant figure out a way to define it in code, without
having to make it like I have. I will soon be trying to  import the hole as
a seperate svg and then distributing it across the empty board. But I
haven't had the time lately unfortunatly. Feel free to optimize if you
can/know how to.

-Benjamin
